"""initial schema

Revision ID: 24de5f26e874
Revises: 
Create Date: 2026-08-13 16:30:50.306144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24de5f26e874'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('template_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('preference_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('notification_delivery_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_delivery_logs')
    op.drop_table('user_notification_preferences')
    op.drop_table('notifications')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
