from enum import Enum


class ItemDonationStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    SUBMITTED = "SUBMITTED"  # legacy alias
    UNDER_REVIEW = "UNDER_REVIEW"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    AVAILABLE = "AVAILABLE"
    REQUESTED = "REQUESTED"
    RESERVED = "RESERVED"
    ACCEPTED = "ACCEPTED"
    FULFILLMENT_IN_PROGRESS = "FULFILLMENT_IN_PROGRESS"
    COMPLETED = "COMPLETED"
    PICKUP_SCHEDULED = "PICKUP_SCHEDULED"
    RECEIVED = "RECEIVED"
    DISTRIBUTED = "DISTRIBUTED"
    CANCELLED = "CANCELLED"
    LISTED = "LISTED"
    UNAVAILABLE = "UNAVAILABLE"


class ItemDocumentType(str, Enum):
    ITEM_PHOTO = "ITEM_PHOTO"
    INVOICE = "INVOICE"
    OTHER = "OTHER"


class ItemRequestStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    RESERVED = "RESERVED"
    FULFILLMENT_IN_PROGRESS = "FULFILLMENT_IN_PROGRESS"
    COMPLETED = "COMPLETED"


class ItemCondition(str, Enum):
    NEW = "NEW"
    LIKE_NEW = "LIKE_NEW"
    GOOD = "GOOD"
    USED = "USED"
    NEEDS_REPAIR = "NEEDS_REPAIR"


CATALOG_VISIBLE_STATUSES = {
    ItemDonationStatus.AVAILABLE.value,
    ItemDonationStatus.LISTED.value,
    ItemDonationStatus.REQUESTED.value,
}

PENDING_ADMIN_STATUSES = {
    ItemDonationStatus.PENDING_VERIFICATION.value,
    ItemDonationStatus.SUBMITTED.value,
    ItemDonationStatus.UNDER_REVIEW.value,
}
