"""initial schema

Revision ID: 64ee791c8f04
Revises: 
Create Date: 2026-08-13 16:30:47.600004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64ee791c8f04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('line1', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('donation_status_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('donation_id', sa.BigInteger(), nullable=False),
    sa.Column('donation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('fund_pools',
    sa.Column('pool_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pool_name', sa.String(length=150), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('pool_id')
    )
    op.create_table('inventory_items',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('programs',
    sa.Column('program_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('verification_requests',
    sa.Column('request_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('donor_profiles',
    sa.Column('donor_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.PrimaryKeyConstraint('donor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fund_ledger',
    sa.Column('ledger_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['fund_pools.pool_id'], ),
    sa.PrimaryKeyConstraint('ledger_id')
    )
    op.create_table('inventory_transactions',
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.item_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('ngo_profiles',
    sa.Column('ngo_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ngo_name', sa.String(length=150), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('address_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.PrimaryKeyConstraint('ngo_id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('receiver_profiles',
    sa.Column('receiver_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.PrimaryKeyConstraint('receiver_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rejection_reasons',
    sa.Column('reason_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['verification_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reason_id')
    )
    op.create_table('verification_documents',
    sa.Column('document_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['verification_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('verification_status_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['verification_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('assistance_applications',
    sa.Column('application_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['receiver_profiles.receiver_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('beneficiaries',
    sa.Column('beneficiary_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.ngo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beneficiary_id')
    )
    op.create_table('donor_pledges',
    sa.Column('pledge_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('payments_made', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.donor_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('pledge_id')
    )
    op.create_table('item_donations',
    sa.Column('item_donation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pickup_address_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.donor_id'], ),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['addresses.address_id'], ),
    sa.PrimaryKeyConstraint('item_donation_id')
    )
    op.create_table('money_donations',
    sa.Column('donation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('donated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.donor_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('ngo_fund_requests',
    sa.Column('request_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.ngo_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('ngo_item_requests',
    sa.Column('request_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ngo_id', sa.BigInteger(), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.ngo_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('recurring_gifts',
    sa.Column('gift_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('payments_made', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.donor_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.PrimaryKeyConstraint('gift_id')
    )
    op.create_table('allocations',
    sa.Column('allocation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ngo_request_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.item_id'], ),
    sa.ForeignKeyConstraint(['ngo_request_id'], ['ngo_item_requests.request_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('application_status_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['assistance_applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('disbursements',
    sa.Column('disbursement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['assistance_applications.application_id'], ),
    sa.PrimaryKeyConstraint('disbursement_id')
    )
    op.create_table('pickup_schedules',
    sa.Column('pickup_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_donation_id', sa.BigInteger(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['item_donation_id'], ['item_donations.item_donation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pickup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickup_schedules')
    op.drop_table('disbursements')
    op.drop_table('application_status_history')
    op.drop_table('allocations')
    op.drop_table('recurring_gifts')
    op.drop_table('ngo_item_requests')
    op.drop_table('ngo_fund_requests')
    op.drop_table('money_donations')
    op.drop_table('item_donations')
    op.drop_table('donor_pledges')
    op.drop_table('beneficiaries')
    op.drop_table('assistance_applications')
    op.drop_table('verification_status_history')
    op.drop_table('verification_documents')
    op.drop_table('rejection_reasons')
    op.drop_table('receiver_profiles')
    op.drop_table('ngo_profiles')
    op.drop_table('inventory_transactions')
    op.drop_table('fund_ledger')
    op.drop_table('donor_profiles')
    op.drop_table('verification_requests')
    op.drop_table('programs')
    op.drop_table('inventory_items')
    op.drop_table('fund_pools')
    op.drop_table('donation_status_history')
    op.drop_table('addresses')
    # ### end Alembic commands ###
