"""initial core schema

Revision ID: d9e83c3d902f
Revises: 
Create Date: 2026-08-04 09:49:19.289986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9e83c3d902f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('assistance_requests',
    sa.Column('assistance_request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('receiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'MATCHED', 'FULFILLED', 'CLOSED', 'CANCELLED', name='assistance_request_status_enum'), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('assistance_request_id')
    )
    op.create_index(op.f('ix_assistance_requests_receiver_user_id'), 'assistance_requests', ['receiver_user_id'], unique=False)
    op.create_index(op.f('ix_assistance_requests_status'), 'assistance_requests', ['status'], unique=False)
    op.create_table('donations',
    sa.Column('donation_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donor_user_id', sa.Uuid(), nullable=False),
    sa.Column('donation_type', sa.Enum('MONEY', 'ITEM', name='donation_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'CONFIRMED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='donation_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_index(op.f('ix_donations_donor_user_id'), 'donations', ['donor_user_id'], unique=False)
    op.create_index(op.f('ix_donations_status'), 'donations', ['status'], unique=False)
    op.create_table('donor_profiles',
    sa.Column('donor_profile_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', name='profile_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('donor_profile_id')
    )
    op.create_index(op.f('ix_donor_profiles_user_id'), 'donor_profiles', ['user_id'], unique=True)
    op.create_table('fund_pools',
    sa.Column('fund_pool_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=16, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('fund_pool_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ngo_profiles',
    sa.Column('ngo_profile_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('focus_area', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', name='profile_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ngo_profile_id')
    )
    op.create_index(op.f('ix_ngo_profiles_user_id'), 'ngo_profiles', ['user_id'], unique=True)
    op.create_table('receiver_profiles',
    sa.Column('receiver_profile_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', name='profile_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('receiver_profile_id')
    )
    op.create_index(op.f('ix_receiver_profiles_user_id'), 'receiver_profiles', ['user_id'], unique=True)
    op.create_table('verification_rejection_reasons',
    sa.Column('reason_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('reason_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('beneficiaries',
    sa.Column('beneficiary_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('receiver_profile_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_profile_id'], ['receiver_profiles.receiver_profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beneficiary_id')
    )
    op.create_index(op.f('ix_beneficiaries_receiver_profile_id'), 'beneficiaries', ['receiver_profile_id'], unique=False)
    op.create_table('donation_items',
    sa.Column('donation_item_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donation_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('donation_item_id')
    )
    op.create_index(op.f('ix_donation_items_donation_id'), 'donation_items', ['donation_id'], unique=False)
    op.create_table('donation_status_history',
    sa.Column('history_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donation_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'SUBMITTED', 'CONFIRMED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='donation_status_enum'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'SUBMITTED', 'CONFIRMED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='donation_status_enum'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_donation_status_history_donation_id'), 'donation_status_history', ['donation_id'], unique=False)
    op.create_table('fund_disbursements',
    sa.Column('disbursement_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fund_pool_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DISBURSED', 'REJECTED', name='fund_disbursement_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_pool_id'], ['fund_pools.fund_pool_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disbursement_id')
    )
    op.create_index(op.f('ix_fund_disbursements_fund_pool_id'), 'fund_disbursements', ['fund_pool_id'], unique=False)
    op.create_index(op.f('ix_fund_disbursements_status'), 'fund_disbursements', ['status'], unique=False)
    op.create_table('fund_ledger_entries',
    sa.Column('ledger_entry_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fund_pool_id', sa.Uuid(), nullable=False),
    sa.Column('donation_id', sa.Uuid(), nullable=True),
    sa.Column('entry_type', sa.Enum('CREDIT', 'DEBIT', name='fund_ledger_entry_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fund_pool_id'], ['fund_pools.fund_pool_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_entry_id')
    )
    op.create_index(op.f('ix_fund_ledger_entries_fund_pool_id'), 'fund_ledger_entries', ['fund_pool_id'], unique=False)
    op.create_table('item_donation_details',
    sa.Column('item_donation_detail_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donation_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_address_id', sa.Uuid(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['addresses.address_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('item_donation_detail_id'),
    sa.UniqueConstraint('donation_id')
    )
    op.create_table('money_donation_details',
    sa.Column('money_donation_detail_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donation_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('money_donation_detail_id'),
    sa.UniqueConstraint('donation_id')
    )
    op.create_table('pickup_requests',
    sa.Column('pickup_request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donation_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'SCHEDULED', 'COMPLETED', 'CANCELLED', name='pickup_status_enum'), server_default='REQUESTED', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.donation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pickup_request_id')
    )
    op.create_index(op.f('ix_pickup_requests_donation_id'), 'pickup_requests', ['donation_id'], unique=False)
    op.create_index(op.f('ix_pickup_requests_status'), 'pickup_requests', ['status'], unique=False)
    op.create_table('programs',
    sa.Column('program_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ngo_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', name='program_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_profile_id'], ['ngo_profiles.ngo_profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_index(op.f('ix_programs_ngo_profile_id'), 'programs', ['ngo_profile_id'], unique=False)
    op.create_table('verification_requests',
    sa.Column('verification_request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('DONOR', 'RECEIVER', 'NGO', name='verification_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='verification_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rejection_reason_id'], ['verification_rejection_reasons.reason_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('verification_request_id')
    )
    op.create_index(op.f('ix_verification_requests_entity_id'), 'verification_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_status'), 'verification_requests', ['status'], unique=False)
    op.create_index(op.f('ix_verification_requests_user_id'), 'verification_requests', ['user_id'], unique=False)
    op.create_table('fund_allocations',
    sa.Column('allocation_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('disbursement_id', sa.Uuid(), nullable=False),
    sa.Column('assistance_request_id', sa.Uuid(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistance_request_id'], ['assistance_requests.assistance_request_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disbursement_id'], ['fund_disbursements.disbursement_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_index(op.f('ix_fund_allocations_disbursement_id'), 'fund_allocations', ['disbursement_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('inventory_item_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('donation_item_id', sa.Uuid(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'ALLOCATED', 'DISBURSED', name='inventory_status_enum'), server_default='AVAILABLE', nullable=False),
    sa.Column('warehouse_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_item_id'], ['donation_items.donation_item_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inventory_item_id')
    )
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_table('ngo_assistance_requests',
    sa.Column('ngo_assistance_request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ngo_user_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'MATCHED', 'FULFILLED', 'CLOSED', 'CANCELLED', name='assistance_request_status_enum'), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ngo_assistance_request_id')
    )
    op.create_index(op.f('ix_ngo_assistance_requests_ngo_user_id'), 'ngo_assistance_requests', ['ngo_user_id'], unique=False)
    op.create_index(op.f('ix_ngo_assistance_requests_status'), 'ngo_assistance_requests', ['status'], unique=False)
    op.create_table('verification_documents',
    sa.Column('document_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('verification_request_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('ID_PROOF', 'ADDRESS_PROOF', 'REGISTRATION_CERT', 'PAN', 'OTHER', name='document_type_enum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.verification_request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_verification_documents_verification_request_id'), 'verification_documents', ['verification_request_id'], unique=False)
    op.create_table('verification_history',
    sa.Column('history_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('verification_request_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='verification_status_enum'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='verification_status_enum'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.verification_request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_verification_history_verification_request_id'), 'verification_history', ['verification_request_id'], unique=False)
    op.create_table('inventory_allocations',
    sa.Column('allocation_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('assistance_request_id', sa.Uuid(), nullable=True),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('allocated_to_user_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistance_request_id'], ['assistance_requests.assistance_request_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.inventory_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_index(op.f('ix_inventory_allocations_inventory_item_id'), 'inventory_allocations', ['inventory_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_allocations_inventory_item_id'), table_name='inventory_allocations')
    op.drop_table('inventory_allocations')
    op.drop_index(op.f('ix_verification_history_verification_request_id'), table_name='verification_history')
    op.drop_table('verification_history')
    op.drop_index(op.f('ix_verification_documents_verification_request_id'), table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index(op.f('ix_ngo_assistance_requests_status'), table_name='ngo_assistance_requests')
    op.drop_index(op.f('ix_ngo_assistance_requests_ngo_user_id'), table_name='ngo_assistance_requests')
    op.drop_table('ngo_assistance_requests')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_fund_allocations_disbursement_id'), table_name='fund_allocations')
    op.drop_table('fund_allocations')
    op.drop_index(op.f('ix_verification_requests_user_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_status'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_entity_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_programs_ngo_profile_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_pickup_requests_status'), table_name='pickup_requests')
    op.drop_index(op.f('ix_pickup_requests_donation_id'), table_name='pickup_requests')
    op.drop_table('pickup_requests')
    op.drop_table('money_donation_details')
    op.drop_table('item_donation_details')
    op.drop_index(op.f('ix_fund_ledger_entries_fund_pool_id'), table_name='fund_ledger_entries')
    op.drop_table('fund_ledger_entries')
    op.drop_index(op.f('ix_fund_disbursements_status'), table_name='fund_disbursements')
    op.drop_index(op.f('ix_fund_disbursements_fund_pool_id'), table_name='fund_disbursements')
    op.drop_table('fund_disbursements')
    op.drop_index(op.f('ix_donation_status_history_donation_id'), table_name='donation_status_history')
    op.drop_table('donation_status_history')
    op.drop_index(op.f('ix_donation_items_donation_id'), table_name='donation_items')
    op.drop_table('donation_items')
    op.drop_index(op.f('ix_beneficiaries_receiver_profile_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_table('verification_rejection_reasons')
    op.drop_index(op.f('ix_receiver_profiles_user_id'), table_name='receiver_profiles')
    op.drop_table('receiver_profiles')
    op.drop_index(op.f('ix_ngo_profiles_user_id'), table_name='ngo_profiles')
    op.drop_table('ngo_profiles')
    op.drop_table('fund_pools')
    op.drop_index(op.f('ix_donor_profiles_user_id'), table_name='donor_profiles')
    op.drop_table('donor_profiles')
    op.drop_index(op.f('ix_donations_status'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_user_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_assistance_requests_status'), table_name='assistance_requests')
    op.drop_index(op.f('ix_assistance_requests_receiver_user_id'), table_name='assistance_requests')
    op.drop_table('assistance_requests')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
